### ISSUE TITLE
Errors in Safari

### ISSUE THREAD

**Issue by Haroenv** [DMTSource/daily-stock-forecast#1]
screenshot: 

![](https://i.imgur.com/X5KdDr3.png)

![](https://i.imgur.com/8QC2WzG.png)

**Comment by DMTSource** [comment]
@Haroenv I am unsure if this was a bug or if the Polymer beta did not support Safari at the time. Currently [it appears to be very cross compatible with most browsers](https://www.polymer-project.org/1.0/docs/browsers) so I will work to update the version of Polymer used in DSF. Thank you for the report.

**Comment by DMTSource** [comment]
Polymer 2.0 now implemented, should fix many issues. Was previously using 0.5 I think or something very old
